### ISSUE TITLE
ResDM Automation

### ISSUE THREAD

**Issue by MykeMyke** [MykeMyke/webCalendar#142]
**Stage 1**
- [x] - Check for Resident DM role in website login to grant additional permissions
- [x] - For Resident DMs default Game Variant to Resident DM Schedule, else default to Adventurer's League One Shot
- [ ] - Automatically specify the logic of patron and general release times for Resident DM Schedule games (do not allow adjustment). For all games in February to December:
- Games up to (inc) 15th 2359 UTC release to Patrons on 24th of preceding month at time = to game start time.
- Games for remainder of month release to Patrons on 25th of preceding month at time = to game start time.
- For games in January as above but release on 22nd and 23rd of preceding month (to clear Xmas).
- All games release to general on 28th of preceding month at time = to game start time.

**Stage 2**
- [ ] Provide a view on Resident DM members area with a table of games entered for next month (to assist with planning). This could be adapted from the existing dashboard (Myke)
- [ ] View to create discord monthly schedule post, comprised of the following:
- Header Text - defined and saved. Reused every month.
- Flavour Text - changes month by month, entered by text entry field.
- Game Schedule Details - generate from Resident DM Schedule type games for the next month: time/date, tier, module code, module name, DM, duration.
- Footer Text - defined and saved. Reused every month.
- [If Daemoxia points me to session-log template post, Myke can make this]
- [ ] Button to generate markdown of above and copy to clipboard
- [ ] Button to send preview of above as DM from bot to requester to visually proof

**Stage 3**
- [ ] Add button to the view of games entered for next month next to each ResDM to send a Discord DM reminder to enter games with a link to the member area on website
- [ ] Add a table to the view of games entered for next month summing the number of games per tier and per ResDM
